### ISSUE TITLE
Criar GET e POST de precificação

### ISSUE THREAD

**Issue by igorbatistadev** [igorbatistadev/confeitaria-backend-poo#5]
Deve incluir os seguintes endpoints:
- 
- GET /api/precificacao - Para listar todas precificações
- POST /api/precificacao - Para salvar uma precificação

É importante ressaltar que na regra de negócio sobre precificação o cliente da aplicação deve passar a descrição da precificação, margem de lucro como 0.20 ou 0.30, caso não seja passado a margem no POST deve usar como padrão 0.30 que é 30%. Deve passar também uma lista contendo os materais utilizados, passado o id do material e a quantidade da porção utilizada.

Com essas informações deve ser feito o calculo da precificação, com base no preço do material feito na compra, deve calcular o custo de acordo com a quantidade utilizada, para gerar o custo total da precificação e sugerir um valor de venda com uma margem de lucro como mencionado anteriormente.

**Comment by rayannegomes** [comment]
Feito.
